# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddItineraryWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddItineraryWindow(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Add Itinerary")
        Dialog.resize(640, 480)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        Dialog.setSizeGripEnabled(False)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 640, 80))
        self.frame.setStyleSheet("background-color: rgb(42, 174, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 60, 50))
        self.pushButton.setStyleSheet("QPushButton{\n"
"color: white;\n"
"    background-color: rgb(42, 174, 255);\n"
"    border: none;\n"
"font: 16pt;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(35, 148, 213);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(25, 105, 152);\n"
"}")
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(170, 15, 260, 50))
        self.label.setStyleSheet("QLabel{\n"
"background-color: rgb(42, 174, 255);\n"
"font: 16pt;\n"
"color: white;\n"
"}")
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(0, 80, 641, 401))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(560, 330, 50, 50))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"color: white;\n"
"background-color: rgb(150, 150, 150);\n"
"border-color: rgb(42, 174, 255);\n"
"font: 16pt;\n"
"border-radius: 25px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(116, 116, 116);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(0,0,0);\n"
"}")
        self.pushButton_2.setDefault(False)
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(40, 20, 531, 221))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 500, 30))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"}")
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 60, 500, 30))
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"}")
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.dateEdit = QtWidgets.QDateEdit(self.frame_3)
        self.dateEdit.setGeometry(QtCore.QRect(140, 110, 370, 30))
        self.dateEdit.setStyleSheet("QDateEdit\n"
"{\n"
"border : 2px solid black;\n"
"background-color : white;\n"
"padding : 5px;\n"
"    border-left-color: rgb(255, 255, 255);\n"
"border-top-right-radius: 10px;\n"
"border-bottom-right-radius: 10px;\n"
"}")
        self.dateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2023, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setObjectName("dateEdit")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 160, 500, 30))
        self.lineEdit_4.setStyleSheet("QLineEdit{\n"
"    border: 2px solid rgb(0, 0, 0);\n"
"    border-radius: 10px;\n"
"}")
        self.lineEdit_4.setClearButtonEnabled(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_4.raise_()
        self.dateEdit.raise_()
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(50, 130, 131, 30))
        self.label_2.setStyleSheet("QLabel{\n"
"border-Left: 2px solid black;\n"
"border-Top: 2px solid black;\n"
"border-Bottom: 2px solid black;\n"
"border-bottom-left-radius: 10px;\n"
"border-top-left-radius: 10px;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.frame_3.raise_()
        self.pushButton_2.raise_()
        self.label_2.raise_()
        self.frame_2.raise_()
        self.frame.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "X"))
        self.label.setText(_translate("Dialog", "Itinerary Planner"))
        self.pushButton_2.setText(_translate("Dialog", "+"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "Masukkan Daerah Wisata"))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog", "Masukkan Objek Wisata"))
        self.lineEdit_4.setPlaceholderText(_translate("Dialog", "Pilih Transportasi"))
        self.label_2.setText(_translate("Dialog", "Tanggal Kunjungan:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_AddItineraryWindow()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
