# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DaerahWisataDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Database

class Ui_DaerahWisataDialog(object):
    table=[]
    def setupUi(self, Dialog, namaDaerah):
        self.table=Database.Database.search("ObjekWisata",starts_with=True,NamaDaerah=str(namaDaerah))
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 578)
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 801, 571))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 799, 569))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        if len(self.table)!=0:
            for element in self.table:
                self.createNewWidget(element[0],element[1],element[2])
        else:
            self.createNewWidget("Tidak ada objek wisata","-","-")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def createNewWidget(self,namaObjekWisata,namaDaerah,informasiObjekWisata):
        newObjekWisata="objekWisataFrame"+str(len(self.table))
        newVertical="verticalName"+str(len(self.table))
        newNamaObjekWisata=namaObjekWisata
        newNamaDaerah=namaDaerah
        newInformasiObjekWisata=informasiObjekWisata

        self.objekWisataFrame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.objekWisataFrame.sizePolicy().hasHeightForWidth())
        self.objekWisataFrame.setSizePolicy(sizePolicy)
        self.objekWisataFrame.setMinimumSize(QtCore.QSize(800, 150))
        self.objekWisataFrame.setMaximumSize(QtCore.QSize(800, 150))
        self.objekWisataFrame.setStyleSheet("#"+newObjekWisata+"{\n"
"background-color: white;\n"
"border: 1px solid black;\n"
"}")
        self.objekWisataFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.objekWisataFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.objekWisataFrame.setObjectName(newObjekWisata)
        self.verticalLayout = QtWidgets.QVBoxLayout(self.objekWisataFrame)
        self.verticalLayout.setObjectName(newVertical)
        self.namaObjekWisataLabel = QtWidgets.QLabel(self.objekWisataFrame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)

        self.namaObjekWisataLabel.setFont(font)
        self.namaObjekWisataLabel.setObjectName(newNamaObjekWisata)
        self.namaObjekWisataLabel.setText(newNamaObjekWisata)
        self.verticalLayout.addWidget(self.namaObjekWisataLabel)

        self.namaDaerahLabel = QtWidgets.QLabel(self.objekWisataFrame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.namaDaerahLabel.setFont(font)
        self.namaDaerahLabel.setObjectName(newNamaDaerah)
        self.namaDaerahLabel.setText(newNamaDaerah)
        self.verticalLayout.addWidget(self.namaDaerahLabel)

        self.informasiObjekWisataLabel = QtWidgets.QLabel(self.objekWisataFrame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.informasiObjekWisataLabel.setFont(font)
        self.informasiObjekWisataLabel.setObjectName(newInformasiObjekWisata)
        self.informasiObjekWisataLabel.setText(newInformasiObjekWisata)
        self.verticalLayout.addWidget(self.informasiObjekWisataLabel)

        self.verticalLayout_3.addWidget(self.objekWisataFrame,QtCore.Qt.AlignTop)
        self.objekWisataFrame=QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.objekWisataFrame.setMinimumSize(QtCore.QSize(745, 0))
        self.objekWisataFrame.setMaximumSize(QtCore.QSize(745, 50))
        self.objekWisataFrame.setStyleSheet("background-color: white;")
        self.objekWisataFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.objekWisataFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.objekWisataFrame.setObjectName(newObjekWisata)
        self.verticalLayout_3.addWidget(self.objekWisataFrame)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.addStretch()
        

        setattr(self,newObjekWisata,self.objekWisataFrame)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_DaerahWisataDialog()
    ui.setupUi(Dialog,"bandung")
    Dialog.show()
    sys.exit(app.exec_())
