# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'riwayatwidgetbaru.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(650, 255)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 631, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(20, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.objekwisata = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.objekwisata.setFont(font)
        self.objekwisata.setObjectName("objekwisata")
        self.verticalLayout.addWidget(self.objekwisata)
        self.DaerahWisata = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.DaerahWisata.setFont(font)
        self.DaerahWisata.setObjectName("DaerahWisata")
        self.verticalLayout.addWidget(self.DaerahWisata)
        self.TanggalTravel = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.TanggalTravel.setFont(font)
        self.TanggalTravel.setStyleSheet("color:rgb(0, 0, 0)")
        self.TanggalTravel.setObjectName("TanggalTravel")
        self.verticalLayout.addWidget(self.TanggalTravel)
        self.Transportasi = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Transportasi.setFont(font)
        self.Transportasi.setStyleSheet("\n"
"color: rgb(0, 0, 0);")
        self.Transportasi.setObjectName("Transportasi")
        self.verticalLayout.addWidget(self.Transportasi)
        self.Ubah = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setUnderline(True)
        self.Ubah.setFont(font)
        self.Ubah.setStyleSheet("color:rgb(12, 190, 255)")
        self.Ubah.setObjectName("Ubah")
        self.verticalLayout.addWidget(self.Ubah)
        self.Hapus = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setUnderline(True)
        self.Hapus.setFont(font)
        self.Hapus.setStyleSheet("color:rgb(12, 190, 255)")
        self.Hapus.setObjectName("Hapus")
        self.verticalLayout.addWidget(self.Hapus)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.objekwisata.setText(_translate("Form", "Objek Wisata"))
        self.DaerahWisata.setText(_translate("Form", "Daerah Wisata"))
        self.TanggalTravel.setText(_translate("Form", "Tanggal Travel"))
        self.Transportasi.setText(_translate("Form", "Transportasi"))
        self.Ubah.setText(_translate("Form", "Ubah"))
        self.Hapus.setText(_translate("Form", "Hapus"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
