# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ObjekWisataInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Database

class Ui_ObjekWisata(object):
    objekWisataTable=Database.Database.search("ObjekWisata")
    def setupUi(self, ObjekWisata):
        ObjekWisata.setObjectName("ObjekWisata")
        ObjekWisata.resize(800, 578)
        self.centralwidget = QtWidgets.QWidget(ObjekWisata)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 801, 80))
        self.frame.setStyleSheet("background-color: rgb(42, 174, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 60, 50))
        self.pushButton.setStyleSheet("QPushButton{\n"
"color: white;\n"
"    background-color: rgb(42, 174, 255);\n"
"    border: none;\n"
"font: 16pt;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(35, 148, 213);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(25, 105, 152);\n"
"}")
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(220, 10, 371, 50))
        self.label.setStyleSheet("QLabel{\n"
"background-color: rgb(42, 174, 255);\n"
"font: 16pt;\n"
"color: white;\n"
"}")
        #>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
        self.pushButton_2 = QtWidgets.QPushButton(self.frame, clicked = lambda: self.searchButtonClicked(ObjekWisata))
        self.pushButton_2.setGeometry(QtCore.QRect(710, 47, 93, 41))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"color: white;\n"
"    background-color: rgb(42, 174, 255);\n"
"    border: none;\n"
"font: 10pt;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(35, 148, 213);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(25, 105, 152);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(70, 50, 641, 31))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setText("")
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        # self.lineEdit.textChanged.connect(self.searchButtonClicked)
        #>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 80, 801, 501))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 799, 499))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_3.setContentsMargins(0, 3, 0, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        ObjekWisata.setCentralWidget(self.centralwidget)
        #self.pushButton_2.clicked.connect(self.searchButtonClicked)

        
        # self.createNewWidget(self.objekWisataTable[1][0],self.objekWisataTable[1][1],self.objekWisataTable[1][2])
        self.retranslateUi(ObjekWisata)
        QtCore.QMetaObject.connectSlotsByName(ObjekWisata)

        for e in self.objekWisataTable:
            self.createNewWidget(e[0],e[1],e[2])
            self.retranslateUi(ObjekWisata)

        

    def createNewWidget(self,namaObjekWisata,namaDaerah,informasiObjekWisata):
        newObjekWisata="objekWisataFrame"+str(len(self.objekWisataTable))
        newVertical="verticalName"+str(len(self.objekWisataTable))
        newNamaObjekWisata=namaObjekWisata
        newNamaDaerah=namaDaerah
        newInformasiObjekWisata=informasiObjekWisata

        self.objekWisataFrame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.objekWisataFrame.sizePolicy().hasHeightForWidth())
        self.objekWisataFrame.setSizePolicy(sizePolicy)
        self.objekWisataFrame.setMinimumSize(QtCore.QSize(800, 150))
        self.objekWisataFrame.setMaximumSize(QtCore.QSize(800, 150))
        self.objekWisataFrame.setStyleSheet("#"+newObjekWisata+"{\n"
"background-color: white;\n"
"border: 1px solid black;\n"
"}")
        self.objekWisataFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.objekWisataFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.objekWisataFrame.setObjectName(newObjekWisata)
        self.verticalLayout = QtWidgets.QVBoxLayout(self.objekWisataFrame)
        self.verticalLayout.setObjectName(newVertical)
        self.namaObjekWisataLabel = QtWidgets.QLabel(self.objekWisataFrame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)

        self.namaObjekWisataLabel.setFont(font)
        self.namaObjekWisataLabel.setObjectName(newNamaObjekWisata)
        self.namaObjekWisataLabel.setText(newNamaObjekWisata)
        self.verticalLayout.addWidget(self.namaObjekWisataLabel)

        self.namaDaerahLabel = QtWidgets.QLabel(self.objekWisataFrame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.namaDaerahLabel.setFont(font)
        self.namaDaerahLabel.setObjectName(newNamaDaerah)
        self.namaDaerahLabel.setText(newNamaDaerah)
        self.verticalLayout.addWidget(self.namaDaerahLabel)

        self.informasiObjekWisataLabel = QtWidgets.QLabel(self.objekWisataFrame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.informasiObjekWisataLabel.setFont(font)
        self.informasiObjekWisataLabel.setObjectName(newInformasiObjekWisata)
        self.informasiObjekWisataLabel.setText(newInformasiObjekWisata)
        self.verticalLayout.addWidget(self.informasiObjekWisataLabel)

        self.verticalLayout_3.addWidget(self.objekWisataFrame,QtCore.Qt.AlignTop)
        self.objekWisataFrame=QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.objekWisataFrame.setMinimumSize(QtCore.QSize(745, 0))
        self.objekWisataFrame.setMaximumSize(QtCore.QSize(745, 50))
        self.objekWisataFrame.setStyleSheet("background-color: white;")
        self.objekWisataFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.objekWisataFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.objekWisataFrame.setObjectName(newObjekWisata)
        self.verticalLayout_3.addWidget(self.objekWisataFrame)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.addStretch()
        

        setattr(self,newObjekWisata,self.objekWisataFrame)

    def retranslateUi(self, ObjekWisata):
        _translate = QtCore.QCoreApplication.translate
        ObjekWisata.setWindowTitle(_translate("ObjekWisata", "MainWindow"))
        self.pushButton.setText(_translate("ObjekWisata", "X"))
        self.label.setText(_translate("ObjekWisata", "Objek Wisata"))
        self.pushButton_2.setText(_translate("ObjekWisata", "Search!"))
        self.lineEdit.setPlaceholderText(_translate("ObjekWisata", "Cari Objek Wisata"))
    
    def searchButtonClicked(self, ObjekWisata):
        searchText=self.lineEdit.text()
        for cnt in reversed(range(self.verticalLayout_3.count())):
            # takeAt does both the jobs of itemAt and removeWidget
            # namely it removes an item and returns it
                widget = self.verticalLayout_3.takeAt(cnt).widget()

                if widget is not None: 
                    # widget will be None if the item is a layout
                    widget.deleteLater()
        if searchText!="":
            searchedObjekWisata=Database.Database.search("ObjekWisata",contains=True,NamaObjekWisata=searchText)
            for el in searchedObjekWisata:
                self.createNewWidget(el[0],el[1],el[2])
                self.retranslateUi(ObjekWisata)
        else:
            for e in self.objekWisataTable:
                self.createNewWidget(e[0],e[1],e[2])
                self.retranslateUi(ObjekWisata)

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     ObjekWisata = QtWidgets.QMainWindow()
#     ui = Ui_ObjekWisata()
#     ui.setupUi(ObjekWisata)
#     ObjekWisata.show()
#     sys.exit(app.exec_())
