# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StartPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from AddItineraryWindow import Ui_Dialog
from ui_RiwayatInterface import Ui_Riwayat
from DaerahWisataInterface import Ui_DaerahWisata
from ObjekWisataInterface import Ui_ObjekWisata
from TransportasiInterface import Ui_Transportasi


class Ui_StartWindow(object):
    
    searchMode = 0 #ObjekWisata: 0 ; DaerahWisata: 1

    def openNewItinerary(self):
        self.itineraryWindow = QtWidgets.QMainWindow()
        self.itineraryUi = Ui_Dialog()
        self.itineraryUi.setupUi(self.itineraryWindow)
        self.itineraryWindow.show()
    
    def openRiwayat(self):
        self.riwayatWindow = QtWidgets.QMainWindow()
        self.riwayatUi = Ui_Riwayat()
        self.riwayatUi.setupUi(self.riwayatWindow)
        self.riwayatWindow.show()

    def searchBarEnter(self):
        self.searchWindow = QtWidgets.QMainWindow()
        if(self.comboBox.currentText() == "Daerah Wisata"):
                self.searchUi = Ui_DaerahWisata()
        else:
                self.searchUi = Ui_ObjekWisata()
        self.searchUi.setupUi(self.searchWindow)
        self.searchUi.lineEdit.setText(self.SearchBar.text())
        self.searchUi.searchButtonClicked(self.searchWindow)
        self.searchWindow.show()

    def openObjekWisata(self):
        self.objekWindow = QtWidgets.QMainWindow()
        self.objekUi = Ui_ObjekWisata()
        self.objekUi.setupUi(self.objekWindow)
        self.objekWindow.show()

    def openDaerahWisata(self):
        self.daerahWindow = QtWidgets.QMainWindow()
        self.daerahUi = Ui_DaerahWisata()
        self.daerahUi.setupUi(self.daerahWindow)
        self.daerahWindow.show()

    def openTransportasi(self):
        self.transportasiWindow = QtWidgets.QMainWindow()
        self.transportasiUi = Ui_Transportasi()
        self.transportasiUi.setupUi(self.transportasiWindow)
        self.transportasiWindow.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(824, 672)
        MainWindow.setStyleSheet("background-color: rgb(42, 153, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.SearchBar = QtWidgets.QLineEdit(self.centralwidget)
        self.SearchBar.setGeometry(QtCore.QRect(220, 320, 461, 61))
        font = QtGui.QFont()
        font.setFamily("Javanese Text")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.SearchBar.setFont(font)
        self.SearchBar.setStyleSheet("border-radius: 20px;\n"
"background: white;\n"
"padding: 8 20 px")
        self.SearchBar.setText("")
        self.SearchBar.setFrame(False)
        self.SearchBar.setObjectName("SearchBar")
        self.ExtraLabel = QtWidgets.QLabel(self.centralwidget)
        self.ExtraLabel.setGeometry(QtCore.QRect(170, 320, 161, 61))
        self.ExtraLabel.setStyleSheet("border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);")
        self.ExtraLabel.setText("")
        self.ExtraLabel.setScaledContents(True)
        self.ExtraLabel.setWordWrap(True)
        self.ExtraLabel.setObjectName("ExtraLabel")
        self.SearchIconLabel = QtWidgets.QLabel(self.centralwidget)
        self.SearchIconLabel.setGeometry(QtCore.QRect(190, 336, 31, 31))
        self.SearchIconLabel.setStyleSheet("border-radius: 20px;\n"
"background-color: rgb(255, 255, 255);")
        self.SearchIconLabel.setText("")
        self.SearchIconLabel.setPixmap(QtGui.QPixmap("C:/Users/S W I F T  X/Downloads/search-26242.png"))
        self.SearchIconLabel.setScaledContents(True)
        self.SearchIconLabel.setWordWrap(True)
        self.SearchIconLabel.setObjectName("SearchIconLabel")
        self.TitleLabel = QtWidgets.QLabel(self.centralwidget)
        self.TitleLabel.setGeometry(QtCore.QRect(-10, 20, 841, 221))
        font = QtGui.QFont()
        font.setFamily("Javanese Text")
        font.setPointSize(24)
        self.TitleLabel.setFont(font)
        self.TitleLabel.setStyleSheet("color: white;")
        self.TitleLabel.setTextFormat(QtCore.Qt.RichText)
        self.TitleLabel.setScaledContents(True)
        self.TitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.TitleLabel.setWordWrap(True)
        self.TitleLabel.setIndent(-1)
        self.TitleLabel.setObjectName("TitleLabel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 280, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Javanese Text")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;")
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(540, 280, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Javanese Text")
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("#comboBox {\n"
"    color: white;\n"
"    border: 0px;\n"
"    padding-left: 5px;\n"
"    padding-top: 5px\n"
"}\n"
"\n"
"#comboBox::ListView {\n"
"    color:white;\n"
"}\n"
"\n"
"QListView{\n"
"    color:black;\n"
"    background-color:white;\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.SearchBar.returnPressed.connect(self.searchBarEnter)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openNewItinerary())
        self.pushButton.setGeometry(QtCore.QRect(190, 440, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Javanese Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: white;\n"
"\n"
"border-radius: 15px;\n"
"\n"
"padding-top:5px;")
        self.pushButton.setObjectName("pushButton")

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openRiwayat())
        self.pushButton_2.setGeometry(QtCore.QRect(480, 440, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Javanese Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("border-style:outset;\n"
"color:white;\n"
"border-color: white;\n"
"border-width: 3px;\n"
"border-radius: 15px;\n"
"padding-top:5px;")
        self.pushButton_2.setObjectName("pushButton_2")

        self.ObjekWisataButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openObjekWisata())
        self.ObjekWisataButton.setGeometry(QtCore.QRect(80, 550, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Javanese Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ObjekWisataButton.setFont(font)
        self.ObjekWisataButton.setStyleSheet("background-color: white;\n"
"\n"
"border-radius: 15px;\n"
"\n"
"padding-top:5px;")
        self.ObjekWisataButton.setObjectName("ObjekWisataButton")
        self.DaerahWisataButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openDaerahWisata())
        self.DaerahWisataButton.setGeometry(QtCore.QRect(330, 550, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Javanese Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DaerahWisataButton.setFont(font)
        self.DaerahWisataButton.setStyleSheet("background-color: white;\n"
"\n"
"border-radius: 15px;\n"
"\n"
"padding-top:5px;")
        self.DaerahWisataButton.setObjectName("DaerahWisataButton")
        self.TransportasiButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openTransportasi())
        self.TransportasiButton.setGeometry(QtCore.QRect(610, 550, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Javanese Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.TransportasiButton.setFont(font)
        self.TransportasiButton.setStyleSheet("background-color: white;\n"
"\n"
"border-radius: 15px;\n"
"\n"
"padding-top:5px;")
        self.TransportasiButton.setObjectName("TransportasiButton")

        self.ObjekWisataButton.raise_()
        self.DaerahWisataButton.raise_()
        self.TransportasiButton.raise_()
        self.label.raise_()
        self.TitleLabel.raise_()
        self.ExtraLabel.raise_()
        self.SearchBar.raise_()
        self.SearchIconLabel.raise_()
        self.comboBox.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



        
            

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SearchBar.setPlaceholderText(_translate("MainWindow", "Gedung Sate"))
        self.TitleLabel.setText(_translate("MainWindow", "Travel Itinerary Planner"))
        self.label.setText(_translate("MainWindow", "Sedang mencari apa?"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Objek Wisata"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Daerah Wisata"))
        self.pushButton.setText(_translate("MainWindow", "Buat Baru"))
        self.pushButton_2.setText(_translate("MainWindow", "Riwayat"))
        self.ObjekWisataButton.setText(_translate("MainWindow", "Objek Wisata"))
        self.DaerahWisataButton.setText(_translate("MainWindow", "Daerah Wisata"))
        self.TransportasiButton.setText(_translate("MainWindow", "Transportasi"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    start = QtWidgets.QMainWindow()
    ui = Ui_StartWindow()
    ui.setupUi(start)
    start.show()
    sys.exit(app.exec_())
