# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TransportasiInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Database


class Ui_Transportasi(object):
    transportTable=Database.Database.search("Transportasi")
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 578)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 801, 121))
        self.frame.setStyleSheet("background-color: rgb(42, 174, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 60, 50))
        self.pushButton.setStyleSheet("QPushButton{\n"
"color: white;\n"
"    background-color: rgb(42, 174, 255);\n"
"    border: none;\n"
"font: 16pt;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(35, 148, 213);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(25, 105, 152);\n"
"}")
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(220, 0, 371, 50))
        self.label.setStyleSheet("QLabel{\n"
"background-color: rgb(42, 174, 255);\n"
"font: 16pt;\n"
"color: white;\n"
"}")
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(710, 47, 93, 71))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"color: white;\n"
"    background-color: rgb(42, 174, 255);\n"
"    border: none;\n"
"font: 10pt;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(35, 148, 213);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(25, 105, 152);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(70, 50, 641, 31))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setText("")
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        # self.lineEdit.textChanged.connect(self.searchButtonClicked)

        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(70, 90, 641, 31))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        # self.lineEdit_2.textChanged.connect(self.searchButtonClicked)

        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 120, 801, 461))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 799, 459))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.pushButton_2.clicked.connect(lambda: self.searchButtonClicked(MainWindow))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        for e in self.transportTable:
            self.createNewWidget(e[1],e[2],e[3],str(e[4]))

    def createNewWidget(self,namaTransport,LokasiBerangkat,LokasiTujuan,Harga):
        newTransport="transportFrame"+str(len(self.transportTable))
        newVertical="verticalName"+str(len(self.transportTable))
        newNamaTransport=namaTransport
        newLokasiBerangkat=LokasiBerangkat
        newLokasiTujuan=LokasiTujuan
        newHarga=Harga

        self.transportFrame=QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.transportFrame.sizePolicy().hasHeightForWidth())
        self.transportFrame.setSizePolicy(sizePolicy)
        self.transportFrame.setMinimumSize(QtCore.QSize(800, 150))
        self.transportFrame.setMaximumSize(QtCore.QSize(800, 150))
        self.transportFrame.setStyleSheet("#" + newTransport + "{\n"
"background-color: white;\n"
"border: 1px solid black;\n"
"}")
        self.transportFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.transportFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.transportFrame.setObjectName(newTransport)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.transportFrame)
        self.verticalLayout_4.setObjectName(newVertical)
        self.namaTransportLabel=QtWidgets.QLabel(self.transportFrame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)

        self.namaTransportLabel.setFont(font)
        self.namaTransportLabel.setObjectName(newNamaTransport)
        self.namaTransportLabel.setText(newNamaTransport)
        self.verticalLayout_4.addWidget(self.namaTransportLabel)

        self.lokasiBerangkatLabel=QtWidgets.QLabel(self.transportFrame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lokasiBerangkatLabel.setFont(font)
        self.lokasiBerangkatLabel.setObjectName(newLokasiBerangkat)
        self.lokasiBerangkatLabel.setText(newLokasiBerangkat)
        self.verticalLayout_4.addWidget(self.lokasiBerangkatLabel)

        self.lokasiTujuanLabel=QtWidgets.QLabel(self.transportFrame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lokasiTujuanLabel.setFont(font)
        self.lokasiTujuanLabel.setObjectName(newLokasiTujuan)
        self.lokasiTujuanLabel.setText(newLokasiTujuan)
        self.verticalLayout_4.addWidget(self.lokasiTujuanLabel)

        self.hargaLabel=QtWidgets.QLabel(self.transportFrame)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.hargaLabel.setFont(font)
        self.hargaLabel.setObjectName(newHarga)
        self.hargaLabel.setText(newHarga)
        self.verticalLayout_4.addWidget(self.hargaLabel)

        self.verticalLayout_3.addWidget(self.transportFrame, 0, QtCore.Qt.AlignTop)
        self.transportFrame=QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.transportFrame.setMinimumSize(QtCore.QSize(745, 0))
        self.transportFrame.setMaximumSize(QtCore.QSize(745, 50))
        self.transportFrame.setStyleSheet("background-color: white;")
        self.transportFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.transportFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.transportFrame.setObjectName(newTransport)
        self.verticalLayout_3.addWidget(self.transportFrame)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.addStretch()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "X"))
        self.label.setText(_translate("MainWindow", "Transportasi"))
        self.pushButton_2.setText(_translate("MainWindow", "Search!"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Cari Lokasi Berangkat"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Cari Lokasi Tujuan"))

    def searchButtonClicked(self, MainWindow):
        searchTextBerangkat=self.lineEdit.text()
        searchTextTujuan=self.lineEdit_2.text()
        for cnt in reversed(range(self.verticalLayout_3.count())):
            # takeAt does both the jobs of itemAt and removeWidget
            # namely it removes an item and returns it
                widget = self.verticalLayout_3.takeAt(cnt).widget()

                if widget is not None: 
                    # widget will be None if the item is a layout
                    widget.deleteLater()
        if searchTextBerangkat!="" and searchTextTujuan!="":
            searchedTransportasi=Database.Database.search("Transportasi",starts_with=True,LokasiBerangkat=searchTextBerangkat, LokasiTujuan=searchTextTujuan)
            if(len(searchedTransportasi)==0):
                self.createNewWidget("Tidak ada transportasi yang ditemukan","","","")
            else:
                rataan=hitungRataan(searchedTransportasi)
                self.createNewWidget("Rataan","Lokasi Berangkat: "+searchTextBerangkat,"Lokasi Berangkat: "+searchTextTujuan,str(rataan))
                for el in searchedTransportasi:
                    self.createNewWidget(el[1],el[2],el[3],str(el[4]))
                    self.retranslateUi(MainWindow)
        elif searchTextBerangkat!="" and searchTextTujuan=="":
            searchedTransportasi=Database.Database.search("Transportasi",starts_with=True,LokasiBerangkat=searchTextBerangkat)
            for el in searchedTransportasi:
                self.createNewWidget(el[1],el[2],el[3],str(el[4]))
                self.retranslateUi(MainWindow)
        elif searchTextBerangkat=="" and searchTextTujuan!="":
            searchedTransportasi=Database.Database.search("Transportasi",starts_with=True,LokasiTujuan=searchTextTujuan)
            for el in searchedTransportasi:
                self.createNewWidget(el[1],el[2],el[3],str(el[4]))
                self.retranslateUi(MainWindow)
        else:
            for el in self.transportTable:
                self.createNewWidget(el[1],el[2],el[3],str(el[4]))
                self.retranslateUi(MainWindow)
        # if searchText!="":
        #     searchedObjekWisata=Database.Database.search("Transportasi",NamaTransportasi=searchText)
        #     for el in searchedObjekWisata:
        #         self.createNewWidget(el[1],el[2],el[3],str(el[4]))
        #         self.retranslateUi(MainWindow)
        # else:
        #     for el in self.transportTable:
        #         self.createNewWidget(el[1],el[2],el[3],str(el[4]))
        #         self.retranslateUi(MainWindow)

def hitungRataan(searchedTransport):
        totalHarga=0
        for el in searchedTransport:
                totalHarga+=el[4]
        return totalHarga/len(searchedTransport)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Transportasi()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
